# Generated by Django 5.2.7 on 2026-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gdpr_consent",
            field=models.BooleanField(default=False, verbose_name="Consentement RGPD"),
        ),
        migrations.AddField(
            model_name="user",
            name="gdpr_consent_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date consentement RGPD"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expiration du token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Token de vérification",
            ),
        ),
    ]
