# Generated by Django 5.2.7 on 2025-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du projet"),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "summary",
                    models.TextField(max_length=500, verbose_name="Résumé court"),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("tech", "Technologies"),
                            ("health", "Santé"),
                            ("education", "Éducation"),
                            ("agriculture", "Agriculture"),
                            ("energy", "Énergie"),
                            ("finance", "Finance"),
                            ("real_estate", "Immobilier"),
                            ("commerce", "Commerce"),
                            ("industry", "Industrie"),
                            ("services", "Services"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "funding_stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idée"),
                            ("prototype", "Prototype"),
                            ("mvp", "MVP"),
                            ("early", "Phase initiale"),
                            ("growth", "Croissance"),
                            ("expansion", "Expansion"),
                        ],
                        max_length=20,
                        verbose_name="Stade de financement",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localisation"),
                ),
                (
                    "funding_goal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant recherché ($)",
                    ),
                ),
                (
                    "current_funding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Financement actuel ($)",
                    ),
                ),
                (
                    "min_investment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Investissement minimum ($)",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/images/",
                        verbose_name="Image principale",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="Lien vidéo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumis"),
                            ("under_review", "En cours d'examen"),
                            ("revision_requested", "Révision demandée"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="Notes de l'administrateur"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de refus"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "favorites_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de favoris"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_plan", "Business Plan"),
                            ("financial", "Document financier"),
                            ("legal", "Document juridique"),
                            ("presentation", "Présentation"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="projects/documents/", verbose_name="Fichier"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de projet",
                "verbose_name_plural": "Documents de projets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
            ],
            options={
                "verbose_name": "Projet favori",
                "verbose_name_plural": "Projets favoris",
                "ordering": ["-created_at"],
            },
        ),
    ]
