# Generated by Django 5.2.7 on 2025-10-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Porteur du projet",
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="projectfavorite",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="projectfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-created_at"], name="projects_pr_created_775fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["sector"], name="projects_pr_sector_c071ba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projectfavorite",
            unique_together={("user", "project")},
        ),
    ]
