# Generated by Django 5.2.7 on 2025-10-29 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant investi ($)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("confirmed", "Confirmé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "investment_date",
                    models.DateField(verbose_name="Date d'investissement"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes administrateur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de déclaration"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Investisseur",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investissement",
                "verbose_name_plural": "Investissements",
                "ordering": ["-investment_date"],
                "indexes": [
                    models.Index(
                        fields=["-investment_date"],
                        name="projects_in_investm_1104cf_idx",
                    ),
                    models.Index(
                        fields=["status"], name="projects_in_status_2bfa98_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Date du rapport")),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Chiffre d'affaires ($)",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Bénéfice ($)",
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Retour sur investissement en pourcentage",
                        max_digits=5,
                        null=True,
                        verbose_name="ROI (%)",
                    ),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Utilisateurs actifs"
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de croissance (%)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, verbose_name="Résumé des performances"
                    ),
                ),
                (
                    "challenges",
                    models.TextField(blank=True, verbose_name="Défis rencontrés"),
                ),
                (
                    "next_objectives",
                    models.TextField(blank=True, verbose_name="Prochains objectifs"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance de projet",
                "verbose_name_plural": "Performances de projets",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["-report_date"], name="projects_pr_report__a1addb_idx"
                    ),
                    models.Index(
                        fields=["project", "-report_date"],
                        name="projects_pr_project_276b38_idx",
                    ),
                ],
                "unique_together": {("project", "report_date")},
            },
        ),
    ]
