# Generated by Django 5.2.7 on 2025-10-29 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_investment_projectperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valeur actuelle de l'investissement (mise à jour périodiquement)",
                max_digits=12,
                verbose_name="Valeur actuelle ($)",
            ),
        ),
    ]
