# Generated by Django 5.2.7 on 2025-10-29 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        verbose_name="Image à la une",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Résumé court de l'article",
                        max_length=300,
                        verbose_name="Extrait",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("published", "Publié")],
                        default="draft",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Séparez les tags par des virgules",
                        max_length=200,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Pour le référencement SEO",
                        max_length=160,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.blogcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="core_blogpo_publish_4753d4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_blogpo_status_032da8_idx"
                    ),
                ],
            },
        ),
    ]
