# Generated by Django 5.2.7 on 2025-10-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("validate", "Validation"),
                            ("reject", "Rejet"),
                            ("publish", "Publication"),
                            ("view", "Consultation"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("project", "Projet"),
                            ("investment", "Investissement"),
                            ("blog_post", "Article de blog"),
                            ("blog_category", "Catégorie"),
                            ("message", "Message"),
                            ("notification", "Notification"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="Type d'entité",
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de l'entité"
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entité"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité",
                "verbose_name_plural": "Journal des activités",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_activi_created_3d0bd9_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_activi_user_id_33cb61_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "-created_at"],
                        name="core_activi_entity__e74002_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_activi_action_a01617_idx",
                    ),
                ],
            },
        ),
    ]
