# Generated by Django 5.2.7 on 2025-12-28 11:57

from django.db import migrations


def copy_blog_data(apps, schema_editor):
    """Copy blog data from core app to blog app"""
    # Get models from both apps
    CoreBlogCategory = apps.get_model('core', 'BlogCategory')
    CoreBlogPost = apps.get_model('core', 'BlogPost')
    BlogCategory = apps.get_model('blog', 'Category')
    BlogPost = apps.get_model('blog', 'BlogPost')
    
    # Copy categories
    category_mapping = {}
    for core_cat in CoreBlogCategory.objects.all():
        new_cat = BlogCategory.objects.create(
            name=core_cat.name,
            slug=core_cat.slug,
            description=core_cat.description,
            created_at=core_cat.created_at,
        )
        category_mapping[core_cat.id] = new_cat
    
    # Copy blog posts
    for core_post in CoreBlogPost.objects.all():
        new_cat = category_mapping.get(core_post.category_id) if core_post.category_id else None
        BlogPost.objects.create(
            title=core_post.title,
            slug=core_post.slug,
            author_id=core_post.author_id,
            category=new_cat,
            featured_image=core_post.featured_image,
            excerpt=core_post.excerpt,
            content=core_post.content,
            status=core_post.status,
            views_count=core_post.views_count,
            created_at=core_post.created_at,
            updated_at=core_post.updated_at,
            published_at=core_post.published_at,
            tags=core_post.tags,
            meta_description=core_post.meta_description,
        )


def reverse_copy(apps, schema_editor):
    """Reverse migration - delete copied data"""
    BlogCategory = apps.get_model('blog', 'Category')
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogCategory.objects.all().delete()
    BlogPost.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("core", "__latest__"),
    ]

    operations = [
        migrations.RunPython(copy_blog_data, reverse_copy),
    ]
