# Generated by Django 5.2.7 on 2025-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("project_submitted", "Projet soumis"),
                            ("project_approved", "Projet validé"),
                            ("project_rejected", "Projet refusé"),
                            ("project_revision", "Révision demandée"),
                            ("new_message", "Nouveau message"),
                            ("project_favorite", "Projet ajouté aux favoris"),
                            ("profile_update", "Mise à jour du profil"),
                            ("system", "Notification système"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Lien"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lue le"),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
