# Generated by Django 5.2.7 on 2025-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("project_submitted", "Projet soumis"),
                    ("project_approved", "Projet validé"),
                    ("project_rejected", "Projet refusé"),
                    ("project_revision", "Révision demandée"),
                    ("new_message", "Nouveau message"),
                    ("project_favorite", "Projet ajouté aux favoris"),
                    ("investment", "Investissement déclaré"),
                    ("investment_confirmed", "Investissement confirmé"),
                    ("investment_rejected", "Investissement rejeté"),
                    ("profile_update", "Mise à jour du profil"),
                    ("system", "Notification système"),
                ],
                max_length=30,
                verbose_name="Type de notification",
            ),
        ),
    ]
